export { BaseRoutes } from './base.js'
export { AuthRoutes } from './auth.js'
export { DocumentRoutes } from './documents.js'
export { MediaRoutes } from './media.js'
export { UserRoutes } from './users.js'
export { TokenRoutes } from './tokens.js'
export { WebhookRoutes } from './webhooks.js'
export { AuditRoutes } from './audit.js'
export { SearchRoutes } from './search.js'
export { ConfigRoutes } from './config.js'

export type { RouteHandlerConfig } from './types.js'
